### ISSUE TITLE
Multiple Sensors

### ISSUE THREAD

**Issue by deafcru** [HomeKidd/ESP8266-HomeKit-Motion-Sensor-Elgato-Eve#1]
Hi, I just played with the Sensor, worked like charm! Excellent Work!
In order to unhook all my Motion Sensors from the Bridge I was going to switch all my devices to the Homekid-motion Sensor, but Homekid-App says at the second Sensor " Device allready exists"
Is there a way to change the Homekit-QR code for my further devices?

**Comment by HomeKidd** [comment]
Hi! Thanks 🤓

Generating the QR code is very complex, it contains a lot of data but non of them are unique (due to generating the code is complex) This is why HomeKit thinks it already exist.
Solution is simple, enter the code manually 😋

**Comment by deafcru** [comment]
Okay tnx for the fast reply, sorry for this, i did not try ... works fine even with AM312
