### ISSUE TITLE
Getting going with Homekidd 

### ISSUE THREAD

**Issue by jeylites** [HomeKidd/ESP8266-HomeKit-Motion-Sensor-Elgato-Eve#3]
Hi 

I thought I would test this interesting project and I got as far as the LCM AP but no webpage. I get the following pop-up error after awhile. 

![Screenshot 2020-10-14 at 11 02 33 PM](https://user-images.githubusercontent.com/9190080/96008363-110c2000-0e72-11eb-9b90-5cd54703c3cc.png)

**My hardware**
```
Wemos D1 mini 
Mac Osx Catilina
```

**Code line used** 
```
esptool.py -p /dev/cu.usbserial-1460 erase_flash

esptool.py -p/dev/cu.usbserial-1460 --baud 115200 write_flash -fs 4MB -fm dio -ff 40m 0x0 rboot.bin 0x1000 blank_config.bin 0x2000 otaboot.bin
```

**Comment by jeylites** [comment]
@HomeKidd 

also, I realize the blank config bin is empty. Is it suppose to be like that?

**Comment by jeylites** [comment]
There seems to be an issue with OTA upload.. at least it didn't work for me, tested the main.bin, it worked like a charm. 


**Hardware**
```
WEMOS d1 Mini
PIR Motion

```

 **Line**
```
esptool.py -p /dev/cu.usbserial-1460 erase_flash

esptool.py -p /dev/cu.usbserial-1460 --baud 115200 write_flash -fs 4MB -fm dio -ff 40m 0x0000 rboot.bin 0x1000 blank_config.bin 0x2000 main.bin

HomeKidd/ESP8266-HomeKit-Motion-Sensor-Elgato-Eve
```

**Comment by jeylites** [comment]
It would be nice if we could have one of the GPIO pins for LED on Motion.

**Comment by HomeKidd** [comment]
Hi! 
Sorry for the late answer! 
Yes thats the OTA whats not working properly, sadly the OTA part isnt my code and also a lot of people having the same issue with it as you, this is why i’m not using OTA in my latest projects 😬 Flashing the main.bin should work✌️

> also, I realize the blank config bin is empty. Is it suppose to be like that?

Yes, its just a blank file - as i’be mentioned it in the Wiki -, its a default file when flashing with esptool.py ✌️

> It would be nice if we could have one of the GPIO pins for LED on Motion.

GPIO2 is used for the LED, using the built-in one so you can connect an external LED to this GPIO, but keep in mind its active low, not active high by default ✌️

**Comment by jeylites** [comment]
tried the external LED - active low, can't seem to get it working on D3 (GPIO0). LED is always illuminated with or without motion

![Screenshot 2020-10-19 at 11 48 52 PM](https://user-images.githubusercontent.com/9190080/96474914-ebae5600-1265-11eb-9572-457dda44e2e9.png)

**Comment by HomeKidd** [comment]
> tried the external LED - active low, can't seem to get it working on D3 (GPIO0). LED is always illuminated with or without motion
> 
> ![Screenshot 2020-10-19 at 11 48 52 PM](https://user-images.githubusercontent.com/9190080/96474914-ebae5600-1265-11eb-9572-457dda44e2e9.png)

GPIO2 is the built-in LED and this can be used only for External LED and **only** active low!
GPIO0 controls the device boot settings so adding an LED is definitely a bad idea! Also GPIO0 should be connected to a button for resetting the accessory as mentioned in the [Wiki](https://github.com/HomeKidd/ESP8266-HomeKit-Motion-Sensor-Elgato-Eve/wiki/Setup#reset)

**Comment by HomeKidd** [comment]
You can hook up any LED that can be driven from **3.3V**:
* connect the LED's positive pin to 3.3V
* connect the LED's negative pin with the - correct value - resistor to GPIO02 / D4

**You cannot use higher voltage than 3.3V for the LED _(without much more circuitry)_ because the LED/resistor acts like a pullup resistor and the ESP has 3.3V GPIOs so pulling up the pins higher voltages then 3.3V will kill the ESP!** 

![led_hi_lo_thumb](https://user-images.githubusercontent.com/53994826/116382255-01ed2e00-a816-11eb-841f-1e135e160c67.jpg)

Other than that looks like the main problem solved so i close the issue 😄
